package edu.poly.store.domain;
// Generated Dec 4, 2018 4:57:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "Cart",
        schema = "dbo",
        catalog = "ManagerPhone_ASS4"
)
public class Cart implements java.io.Serializable {

    private int cartId;
    private Users users;
    private Date paymentDate;
    private String total;
    private Boolean cartStatus;
    private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);

    public Cart() {
    }

    public Cart(int cartId) {
        this.cartId = cartId;
    }

    public Cart(int cartId, Users users, Date paymentDate, String total, Boolean cartStatus, Set<CartDetail> cartDetails) {
        this.cartId = cartId;
        this.users = users;
        this.paymentDate = paymentDate;
        this.total = total;
        this.cartStatus = cartStatus;
        this.cartDetails = cartDetails;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "CartID", unique = true, nullable = false)
    public int getCartId() {
        return this.cartId;
    }

    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "UsersID")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "PaymentDate", length = 10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    @Column(name = "Total", precision = 53, scale = 0)
    public String getTotal() {
        return this.total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    @Column(name = "CartStatus")
    public Boolean getCartStatus() {
        return this.cartStatus;
    }

    public void setCartStatus(Boolean cartStatus) {
        this.cartStatus = cartStatus;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cart")
    public Set<CartDetail> getCartDetails() {
        return this.cartDetails;
    }

    public void setCartDetails(Set<CartDetail> cartDetails) {
        this.cartDetails = cartDetails;
    }

}
