package edu.poly.store.domain;
// Generated Nov 25, 2018 10:46:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="Cart"
    ,schema="dbo"
    ,catalog="ManagerPhone_ASS_JAVA4"
)
public class Cart  implements java.io.Serializable {


     private int cartId;
     private Users users;
     private Date paymentDate;
     private Double total;
     private Boolean isDelete;
     private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);

    public Cart() {
    }

    public Cart(int cartId) {
        this.cartId = cartId;
    }
    public Cart(int cartId, Users users, Date paymentDate, Double total, Boolean isDelete, Set<CartDetail> cartDetails) {
       this.cartId = cartId;
       this.users = users;
       this.paymentDate = paymentDate;
       this.total = total;
       this.isDelete = isDelete;
       this.cartDetails = cartDetails;
    }
   
     @Id 

    
    @Column(name="CartID", unique=true, nullable=false)
    public int getCartId() {
        return this.cartId;
    }
    
    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UsersID")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PaymentDate", length=10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    
    @Column(name="Total", precision=53, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }

    
    @Column(name="IsDelete")
    public Boolean getIsDelete() {
        return this.isDelete;
    }
    
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<CartDetail> getCartDetails() {
        return this.cartDetails;
    }
    
    public void setCartDetails(Set<CartDetail> cartDetails) {
        this.cartDetails = cartDetails;
    }




}


