package edu.poly.store.domain;
// Generated Dec 4, 2018 4:57:47 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product",
        schema = "dbo",
        catalog = "ManagerPhone_ASS4"
)
public class Product implements java.io.Serializable {

    private int productId;
    private Category category;
    private String productName;
    private String image;
    private String price;
    private Integer quantity;
    private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);

    public Product() {
    }

    public Product(int productId) {
        this.productId = productId;
    }

    public Product(int productId, Category category, String productName, String image, String price, Integer quantity, Set<CartDetail> cartDetails) {
        this.productId = productId;
        this.category = category;
        this.productName = productName;
        this.image = image;
        this.price = price;
        this.quantity = quantity;
        this.cartDetails = cartDetails;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ProductID", unique = true, nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CategoryID")
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Column(name = "ProductName")
    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    @Column(name = "Image")
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "Price", precision = 53, scale = 0)
    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    @Column(name = "Quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
    public Set<CartDetail> getCartDetails() {
        return this.cartDetails;
    }

    public void setCartDetails(Set<CartDetail> cartDetails) {
        this.cartDetails = cartDetails;
    }

}
