package edu.poly.store.domain;
// Generated Dec 4, 2018 9:23:17 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users",
         schema = "dbo",
         catalog = "ManagerPhone"
)
public class Users implements java.io.Serializable {

    private int usersId;
    private String username;
    private String password;
    private String fullName;
    private String numberPhone;
    private String email;
    private Boolean role;
    private String address;
    private Set<Cart> carts = new HashSet<Cart>(0);

    public Users() {
    }

    public Users(int usersId) {
        this.usersId = usersId;
    }

    public Users(int usersId, String username, String password, String fullName, String numberPhone, String email, Boolean role, String address, Set<Cart> carts) {
        this.usersId = usersId;
        this.username = username;
        this.password = password;
        this.fullName = fullName;
        this.numberPhone = numberPhone;
        this.email = email;
        this.role = role;
        this.address = address;
        this.carts = carts;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "UsersID", unique = true, nullable = false)
    public int getUsersId() {
        return this.usersId;
    }

    public void setUsersId(int usersId) {
        this.usersId = usersId;
    }

    @Column(name = "Username")
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "Password")
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "FullName")
    public String getFullName() {
        return this.fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    @Column(name = "NumberPhone")
    public String getNumberPhone() {
        return this.numberPhone;
    }

    public void setNumberPhone(String numberPhone) {
        this.numberPhone = numberPhone;
    }

    @Column(name = "Email")
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Role")
    public Boolean getRole() {
        return this.role;
    }

    public void setRole(Boolean role) {
        this.role = role;
    }

    @Column(name = "Address")
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
    public Set<Cart> getCarts() {
        return this.carts;
    }

    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

}
